---
title: "Figure 4mp"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
```{r install libraries}
# Function to check if pkgs are installed, and install any missing pkgs

pkgTest <- function(x)
{
  if (!require(x,character.only = TRUE))
  {
    install.packages(x,dep=TRUE,repos='http://cran.us.r-project.org')
    if(!require(x,character.only = TRUE)) stop(x, " :Package not found")
  }
}

# create list of required packages
list.of.packages <- c("sf", "dplyr", "ggplot2", "lubridate","orsifronts", "ggOceanMaps",
                      "viridis","ncdf4","raster", "fields","gridExtra",
                      "MASS", "adehabitatLT", "aniMotum") 

# create list of installed packages
pkges = installed.packages()[,"Package"]

# Install and load all required pkgs
for (pk in list.of.packages) {
  pkgTest(pk)
}
```

```{r define functions}
# auxiliary function to bin data by longitude

bin_func<-function(data,  bin_size){
  # bin a vector
  dat<-data.frame(data=data)
  dat.r<-range(pretty(range(dat$data), n=10))
  bins<-seq(from=dat.r[1], by=bin_size, to=dat.r[2])
  n.bins<-length(bins)-1
  dat$index<-1:length(dat$data)
  out<-list()
  for(i in 1:n.bins){
    #print(i)
    dat.b<-dat[dat$data<bins[i+1] & dat$data>bins[i],]
    #print(dim(dat.b))
    # if not data exist in given bin, return 0
    if(dim(dat.b)[1]==0){
      dat.b<-data.frame(data=NA, index=NA, bin=bins[i+1])
      out[[i]]<-dat.b
    } else {
      dat.b$bin<-rep(bins[i+1], dim(dat.b)[1])
      out[[i]]<-dat.b
    }
  }
  out<-do.call("rbind", out)
  out<-out[order(out$index),]
  out<-dplyr::select(out, data, bin)
  out<-na.omit(out)
  out
}

speed_func<-function(dat, vmax=4){
  # calculate speed between known geographic coordinates and times
  dat<-na.omit(dat) # exclude data for which position or time is not known
  xy<-dplyr::select(dat, lon360, lat)
  tdat<-dplyr::select(dat, date)
  nx<-length(tdat$date)
  dist<-na.omit(geosphere::distGeo(xy))
  bear<-na.omit(geosphere::bearing(xy))
  tdiff<-as.numeric(difftime(tdat$date[-1], tdat$date[-nx], units="secs"))
  spd<-as.numeric(na.omit(dist)/tdiff)
  out<-data.frame(date=dat$date[-nx], spp=dat$spp[-nx], lon=xy$lon360[-nx], 
                  lat=xy$lat[-nx], dist=dist, time=tdiff, bear=bear, 
                  speed=spd)
  out<-out[out$speed<=vmax,]
  out
}
```
# main function to tuns above auxiliary functions

```{r define main analysis function}

plot_figure_4mp<-function(){
  # to ensure st_crop function works as intended, implement the line below for now (github.com advice 10/3/2022)
  sf_use_s2(FALSE)
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Import and housekeeping
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
  # set data directories for tracks and environmental layers for final plot
  my_wd<-getwd()
  tracks<-paste(my_wd, "/data/tracks/tracks3.csv", sep="")
  track_sum<-paste(my_wd, "/data/tracks/tagstats3.csv", sep="")
  
  # read in the data, created and exported from the compile_data script
  
  dat <- read.csv(tracks)
  dat<-dat[,-1] #exclude first column
  
  #print(length(unique(dat$id)))
  tt_sum<-read.csv(track_sum)
  tt_sum<-tt_sum[,-1] # exclude first column
  
  bloom_deps<-tt_sum$id[tt_sum$RB2==1]
  dat<-dat[dat$id%in%bloom_deps,]
  
  # subset for months April and beyond
  dat<-dat[dat$month>3,]
  
  dat$date<-as.POSIXct(strptime(dat$date, format="%Y-%m-%d %H:%M:%S", tz="GMT"))
  names(dat)[2]<-"lon"
  names(dat)[3]<-"lat"
  names(dat)[4]<-"lc"
  ##
  #-----------------------------------------------------------------------------------
  # Fit a continuous random walk model
  #--------------------------------------------------------------------------------
  
  # arrange data to fit needed formating
  
  df <- dplyr::select(dat, id, date, lc, lon, lat)

    #------------------------------------------------------------------
  # fit model using a 1-day step
  #------------------------------------------------------------------

  fit <- fit_ssm(df,
                 vmax = 4,   
                 min.dt = 60,      # minimum allowable time difference between observations (in minutes)
                 model = "rw", 
                 time.step = 24)   # the regular time interval, in hours to predict to
  
  #saveRDS(fit, "./output/fit_fit_smm_NB.RDS")
  #fit = readRDS("./output/fit_fit_smm_NB.RDS")
  
  #fit$ssm[[1]]
  #fitted = grab(fit, what = "fitted", as_sf = FALSE)
  predicted  = grab(fit, what = "predicted", as_sf = FALSE)
  
  dff<-aggregate(dat$spp, list(id=dat$id), unique)
  names(dff)[2]<-"spp"
  
  tt<-merge(predicted, dff, by="id", all.y=FALSE)
  #
  zdf<-tt
  # ensure lon is continuous over -189
  zdf$lon360<-ifelse(zdf$lon>0, zdf$lon-360, zdf$lon)
  shift<-25
  zdf$lon360<-zdf$lon360+shift
  
  # estimate mean speeds witht he bespoke speed_func function
  zspd <-
    zdf %>% 
    dplyr::group_by(id) %>%
    dplyr::arrange(date, .by_group=TRUE) %>% 
    tidyr::nest() %>%
    dplyr::mutate(data=purrr::map(data,speed_func))%>%
    tidyr::unnest(cols=c(data))
  
  # shift the longitude back for proper plotting
  zspd$lon360<-zspd$lon-shift
  
  # add longitudinal binning to the data
  zspd_bin<-bin_func(zspd$lon360, 5)
  zspd$bin<-as.factor(zspd_bin$bin)
  
  # sf_zspd<-st_as_sf(zspd, coords=c("lon", "lat"))%>%
  #   st_set_crs(4326)%>%
  #   st_transform(3031)
  # 
  # sf_zspd$month<-lubridate::month(sf_zspd$date)
  # 
  # # split out each spp for plotting
  # ch_sf_zspd<-sf_zspd[sf_zspd$spp=="CHPE",]
  # es_sf_zspd<-sf_zspd[sf_zspd$spp=="SES",]
  
  
  #------------------------------------------------------------------
  # Fit movement persistence model
  #------------------------------------------------------------------
  # 
  fmp <- fit %>%
    grab(what = "predicted", as_sf = FALSE) %>%
    dplyr::select(id, date, lon, lat) %>%
    fit_mpm(model = "jmpm",  ssm_control(optim = "nlminb", verbose=1))
  # # #
  # # # # extract results and merge
  tt<-fmp[[1]][[1]]$fitted
  ttpos<-fmp[[1]][[1]]$data
  tt<-merge(tt, ttpos, by="id")
  tt$DOY<-lubridate::yday(tt$date.x)
  # make longitude continuous (no positive values)
  tt$x360<-ifelse(tt$x>0,  tt$x-360, tt$x)
  # 
  # # create binning category
  tt_bin<-bin_func(tt$x360, 5)
  tt$bin<-as.factor(tt_bin$bin)
  # 
  # #add speices ID back to tt
  spp.key<-data.frame(id=unique(tt$id), spp=c(rep("CHPE", 11), rep("SES", 14)))
  tt<-merge(tt, spp.key, by="id")
  

  tt<-st_as_sf(tt, coords=c("x", "y"))%>%
    st_set_crs(4326)%>%
    st_transform(3031)
  # 
  mypal <- RColorBrewer::brewer.pal(n = 8, name = "YlGnBu")

  m1<-basemap(-50)+
    geom_sf(data=tt, aes(colour=g))+
    scale_color_gradientn(colours = mypal,limits = c(0,1),oob=scales::squish)
  # 
  m1
  windows()
  plot(m1)
  savePlot(filename="Figure_5mp_map.pdf", type="pdf")
  # 
  p3<-ggplot(tt)+
    scale_fill_manual(values=c("#d95f02","#7570b3"), name="Species", labels=c("Chinstrap", "Elephant seal"))+
    geom_boxplot(aes(x=bin, y=g, fill=spp),outlier.shape=NA)+
    coord_cartesian(ylim = quantile(tt$g, c(0, 1)))+
    scale_y_continuous(limits = quantile(tt$g, c(0, 1)))+
    scale_x_discrete(name="Longitude", breaks=seq(from=-220, by=20, to=-60),
                     labels=c("-220","-200","-180","-160","-140","-120","-100","-80","-60"))+
    ylab("Move persistance")+
    theme_bw()

  windows()
  plot(p3)
  savePlot(filename="Figure_5mp_bin.pdf", type="pdf")
  
  p4<-ggplot(zspd)+
    scale_fill_manual(values=c("#d95f02","#7570b3"), name="Species", labels=c("Chinstrap", "Elephant seal"))+
    geom_boxplot(aes(x=bin, y=speed, fill=spp),outlier.shape=NA)+
    coord_cartesian(ylim = quantile(tt$g, c(0, 1)))+
    scale_y_continuous(limits = quantile(tt$g, c(0, 1)))+
    scale_x_discrete(name="Longitude", breaks=seq(from=-220, by=20, to=-60), 
                     labels=c("-220","-200","-180","-160","-140","-120","-100","-80","-60"))+
    ylab("Speed (m/s)")+
    theme_bw()  
  
  windows()
  plot(p4)
  savePlot(filename="Figure_5sp_bin.pdf", type="pdf")
  
  # for each species, estimate mean speed within and outside 120-170W region
  
  zch<-zspd[zspd$spp=="CHPE",]
  zes<-zspd[zspd$spp=="SES",]
  zch$region<-ifelse(zch$lon> -170 & zch$lon< -120, TRUE, FALSE)
  zes$region<-ifelse(zes$lon> -170 & zes$lon< -120, TRUE, FALSE)
    
  tapply(zch$speed, zch$region, mean)
  tapply(zch$speed, zch$region, sd)
  tapply(zes$speed, zes$region, mean)
  tapply(zes$speed, zes$region, sd)
  t.test(speed~region, data=zch)
  t.est(speed~region, data=zes)
  
}


```
# Run the function

```{r run the function}

plot_figure_4mp()


```